### ISSUE TITLE
Clarify that to "Submit" metadata a user must be certified

### ISSUE THREAD

**Issue by xdoan** [Sage-Bionetworks/HTAN-data-ingress-documentation-draft#11]
1) Can you add a requirements at the top of of the metadata annotation steps that a user must be certified? Especially for the submission step!

2) Can you add in the FAQ that a user needs to be certified to upload data AND the metadata templates as they are stored on Synapse?

**Comment by ychae** [comment]
Update from @xdoan:
could you clarify in the FAQ something along the lines of "Any submissions of data or metadata to Synapse can only be completed by a certified user". The definition of "data" is not definied anywhere and people usually think of it for fastqs, etc and not for metadata (though that is subject to a long debate) so I want to make it clear on the FAQ that they are submitting/uploading to Synapse for metadata.
