### ISSUE TITLE
Document removal of 'empty' rows before submission

### ISSUE THREAD

**Issue by adamjtaylor** [Sage-Bionetworks/HTAN-data-ingress-documentation-draft#22]
Per [HTAN-92](https://sagebionetworks.jira.com/browse/HTAN-92), we should clarify that if metadata is being submitted/resubmitted for only some entities, "empty rows" - those containing just a file name and entityId should be removed from the csv before upload and validation - otherwise validation will fail.
This does not appear to be documented in the FAQ so far.

**Comment by ychae** [comment]
Closing as ticket has been moved (https://github.com/ncihtan/HTAN-Data-Ingress-Docs/issues/24)
