### ISSUE TITLE
fix markdown on "Organize Your Data Upload"

### ISSUE THREAD

**Issue by xdoan** [Sage-Bionetworks/HTAN-data-ingress-documentation-draft#9]
https://ncihtan.github.io/HTAN-Data-Ingress-Docs/organize-your-data-upload.html

I see that ## notation instead of the header, so some minor markdown formatting issues.

**Comment by ychae** [comment]
Good catch! It was a whitespace that threw everything off 😩

**Comment by ychae** [comment]
Fixed with https://github.com/ncihtan/HTAN-Data-Ingress-Docs/pull/11
